export const GAME_CONFIG = {
  simulation: {
    fixedStepSeconds: 1 / 60,
    maxSubSteps: 3,
  },
  world: {
    // World-space distances use engine units. Offer distances convert these units to meters below.
    blocksX: 10,
    blocksZ: 10,
    // Center-to-center distance between neighboring roads, in world units.
    blockSize: 240,
    // Total curb-to-curb width and one sidewalk's width, in world units.
    roadWidth: 75,
    sidewalkWidth: 3,
    boundaryPadding: 30,
    spatialCellSize: 64,
    roadMarkings: {
      lineWidth: 0.35,
      lineGap: 1.1,
      intersectionBuffer: 12,
      height: 0.05,
    },
    buildings: {
      lotTargetSize: 55,
      emptyLotChance: 0.16,
      minLotsPerSide: 3,
      buildableInset: 14,
      minLotCoverage: 0.46,
      maxLotCoverage: 0.74,
      lotJitter: 0.11,
      minHeight: 10,
      maxHeight: 44,
      fallbackCoverage: 0.62,
      fallbackHeight: 18,
    },
  },
  player: {
    // Vehicle dimensions and collision radius are in world units.
    length: 10.2,
    width: 5.8,
    // Linear speeds are world units/second; acceleration and braking are world units/second squared.
    acceleration: 18.2,
    highSpeedAcceleration: 4.1,
    accelerationFalloffPower: 1.45,
    reverseAcceleration: 7,
    braking: 22,
    rollingResistance: 0.75,
    aerodynamicDrag: 0.00022,
    // This controls physical top speed. Displayed MPH is this value times mphPerWorldUnitPerSecond.
    maxForwardSpeed: 90,
    maxReverseSpeed: 18,
    // Yaw rates are radians/second. Grip and steering settings control how quickly the car reaches them.
    lowSpeedYawRate: 1.45,
    highSpeedYawRate: 0.68,
    steeringResponse: 5.6,
    counterSteerResponseMultiplier: 1.7,
    minimumSteeringSpeed: 0.6,
    fullSteeringSpeed: 9,
    lateralGrip: 8.5,
    slidingGrip: 1.15,
    maxLateralAcceleration: 46,
    brakeGripLoss: 0.48,
    spinOutTorque: 2.1,
    brakeOversteer: 0.85,
    yawRecovery: 2.8,
    maxYawRate: 2.35,
    collisionSpeedLoss: 0.45,
    sidewalkHandlingMultiplier: 0.5,
    sidewalkGripMultiplier: 0.45,
    sidewalkExtraDrag: 18,
    radius: 3.5,
    damageEffects: {
      accelerationMultiplierAtMaxDamage: 0.28,
      topSpeedMultiplierAtMaxDamage: 0.35,
      reverseMultiplierAtMaxDamage: 0.45,
      brakingMultiplierAtMaxDamage: 0.55,
      yawRateMultiplierAtMaxDamage: 0.55,
      steeringResponseMultiplierAtMaxDamage: 0.45,
      gripMultiplierAtMaxDamage: 0.45,
      yawRecoveryMultiplierAtMaxDamage: 0.55,
      extraDragAtMaxDamage: 2.2,
    },
  },
  input: {
    steeringRiseRate: 4.2,
    steeringReturnRate: 6.5,
    pedalRiseRate: 5,
    pedalReturnRate: 8,
  },
  camera: {
    // Camera distances and look-ahead are in world units. FOV values are radians.
    distance: 30,
    height: 15,
    lookAhead: 18,
    positionDamping: 7.5,
    targetDamping: 9,
    velocityInfluence: 0.16,
    minFov: 0.82,
    maxFov: 0.98,
  },
  traffic: {
    vehicleCount: 120,
    // NPC body and collision dimensions are local width (side-to-side/X) and length (front-to-back/Z).
    vehicleWidth: 5.4,
    vehicleLength: 9.4,
    hitboxWidth: 5.4,
    hitboxLength: 9.4,
    // Traffic speeds are world units/second and use the same MPH conversion as the player.
    minSpeed: 25,
    maxSpeed: 50,
    minSpeedChangeSeconds: 8,
    maxSpeedChangeSeconds: 12,
    acceleration: 4,
    braking: 22,
    turnSpeed: 24,
    turnSlowdownDistance: 75,
    turnCurveRadius: 32,
    turnCurveSegments: 6,
    // Following gaps are bumper-to-bumper world-unit distances. Time headway is in seconds.
    minimumFollowingGap: 8,
    followingTimeHeadway: 0.9,
    followingSpeedCorrection: 1.2,
    sameLaneTolerance: 4.5,
    sameDirectionAlignment: 0.85,
    lookAheadDistance: 85,
    spatialCellSize: 48,
    playerCollisionQueryRadius: 24,
    fullSimulationRadius: 520,
    reducedSimulationRadius: 900,
    reducedUpdateInterval: 0.1,
    recycleRadius: 1200,
    respawnMinRadius: 650,
    respawnMaxRadius: 900,
    damageCooldownSeconds: 0.6,
    // Distance from each road centerline to the center of its directional lane.
    laneOffset: 18.75,
  },
  drivingRules: {
    speedLimitMph: 60,
    speedToleranceMph: 5,
    fullSpeedingMph: 70,
    minimumEvaluationSpeedMph: 3,
    speedingPointsPerSecond: 2,
    wrongSidePointsPerSecond: 5,
    sidewalkPointsPerSecond: 5,
    serviceAreaPadding: 1,
  },
  police: {
    vehicleCount: 10,
    updateIntervalSeconds: 0.1,
    // Vision is the union of a close circle and an oriented cross. Distances are world units.
    visionRadius: 45,
    visionCrossWidth: 60,
    visionForwardLength: 340,
    visionRearLength: 110,
    visionSideLength: 240,
    citationThreshold: 4,
    suspicionDecayPerSecond: 2,
    citationCooldownSeconds: 10,
    // A player-caused impact at or above this speed is a discrete moving violation.
    collisionMinimumImpactSpeedMph: 3,
    collisionFullSeveritySpeedMph: 60,
    collisionViolationPoints: 4,
    // Pursuit movement uses world units/second; the configured speed is about 90 MPH at the current conversion.
    pursuitSpeed: 115,
    pursuitAcceleration: 16,
    pursuitBraking: 24,
    pursuitTurnSpeed: 40,
    // Pursuing officers use this inner lane offset to pass normal traffic while staying on the road.
    pursuitLaneOffset: 8,
    pursuitMinimumFollowingGap: 4,
    pursuitFollowingTimeHeadway: 0.5,
    // U-turn distances are world units. Higher penalties/savings requirements make reversals less frequent.
    pursuitUTurnMinimumBehindDistance: 12,
    pursuitUTurnRequiredRouteSavings: 35,
    pursuitReverseDirectionPenalty: 60,
    pursuitUTurnCooldownSeconds: 3,
    // Once this close to an intersection, an officer finishes the turn it already selected.
    pursuitTurnCommitDistance: 75,
    // Bust and escape ranges are gameplay meters after applying ride.metersPerWorldUnit.
    bustRadiusMeters: 10,
    bustDurationSeconds: 4,
    bustDecaySecondsPerSecond: 1,
    escapeDistanceMeters: 600,
    escapeDurationSeconds: 8,
    minimumFine: 40,
    maximumFine: 150,
  },
  progression: {
    saveKey: "delivery-driver-progression-v1",
    saveVersion: 3,
    startingMoney: 30,
    autosaveSeconds: 1,
    rideHistoryLimit: 100,
    maxUpgradeLevel: 50,
    upgradePercentPerLevel: 0.02,
    upgradeCostBase: 100,
    additionalCostPerUpgradeLevel: 100,
    equipMaxSpeedMph: 1,
    missionLicenseUnlockCosts: {
      rideshare: 0,
      taxi: 300,
      rideshare_silver: 3000,
      package_delivery: 500,
    },
    vehiclePrices: {
      starter: 0,
      "used-compact": 2000,
      "old-sedan": 5000,
      hatchback: 11000,
      "modern-sedan": 18000,
      "sport-compact": 27000,
      "touring-sedan": 38000,
      "hot-hatch": 52000,
      coupe: 70000,
      "muscle-car": 90000,
      "sport-sedan": 115000,
      "performance-coupe": 140000,
      "grand-tourer": 165000,
      "exotic-coupe": 195000,
      supercar: 220000,
      "elite-sports-car": 250000,
    },
    eliteVehicleStats: {
      acceleration: 24,
      topSpeed: 157.5,
      turning: 1.3,
      braking: 28,
    },
  },
  fuel: {
    capacitySecondsAtCruise: 500,
    lowFuelThreshold: 0.2,
    refuelRadius: 16,
    refuelRatePerSecond: 0.2,
    fullTankCost: 30,
    refuelStopSpeedMph: 1,
    idleDrainMultiplier: 0.08,
    minMovingDrainMultiplier: 0.35,
    speedDrainMultiplier: 1.35,
    stationCount: 7,
  },
  repair: {
    shopCount: 3,
    repairRadius: 16,
    repairRatePerSecond: 0.2,
    fullRepairCost: 200,
    repairStopSpeedMph: 1,
    damageScaleSpeedMph: 60,
    maxCollisionDamage: 0.26,
  },
  map: {
    refreshSeconds: 0.5,
  },
  packageDelivery: {
    offerSeed: 31991,
    ratePerMeter: 0.08,
    fareDecayPercentPerSecond: 0.005,
    // Offer-generation distances are meters after applying ride.metersPerWorldUnit.
    maxPickupDistance: 1200,
    minDropoffDistance: 1400,
    maxDropoffDistance: 2400,
    // Arrival radii are physical world units so marker size and collision distance stay aligned.
    pickupRadius: 7,
    dropoffRadius: 7,
    possessionFine: 200,
    resultSeconds: 3,
  },
  ride: {
    offerCount: 3,
    offerLifetimeSeconds: 60,
    offerDistanceRefreshSeconds: 1,
    maxPickupDistance: 400,
    minTripDistance: 350,
    // Trip-tier distances are meters after applying metersPerWorldUnit.
    tripTiers: {
      short: {
        minDistance: 350,
        maxDistance: 650,
      },
      medium: {
        minDistance: 660,
        maxDistance: 1100,
      },
      long: {
        minDistance: 1101,
        maxDistance: 2200,
      },
    },
    // Offer distances = world distance * this value. It does not change physical vehicle motion.
    metersPerWorldUnit: 1,
    // Displayed MPH = physical speed in world units/second * this value. Changing it also changes
    // speed-based rules and damage because those systems intentionally consume the displayed MPH.
    mphPerWorldUnitPerSecond: 0.78,
    // Arrival radii remain physical world units.
    pickupRadius: 7,
    destinationRadius: 7,
    maximumArrivalSpeedMph: 5,
    rideResultSeconds: 2,
    fare: {
      baseFare: 9.75,
      ratePerMeter: 0.02,
      pickupDistanceWeight: 0.35,
      randomMultiplierMin: 0.7,
      randomMultiplierMax: 1.3,
      maxTipPercent: 0.5,
      tipDecayPercentPerSecond: 0.005,
      violationTipPenaltyPerPoint: 0.02,
    },
    passengerWeights: {
      normal: 0.65,
      scaredyCat: 0.25,
      speedDemon: 0.1,
    },
    satisfaction: {
      startingScore: 100,
      collisionCooldownSeconds: 5,
      collisionSpeedThresholdMph: 12,
      normal: {
        collisionPenalty: 40,
        maxSafeSpeedMph: 60,
        speedPenaltyPerSecond: 1,
      },
      scaredyCat: {
        collisionPenalty: 60,
        maxSafeSpeedMph: 50,
        speedPenaltyPerSecond: 1,
      },
      speedDemon: {
        collisionPenalty: 10,
        minRequiredSpeedMph: 25,
        speedPenaltyPerSecond: 1,
        gracePeriodSeconds: 5,
      },
    },
  },
} as const;
