export const GAME_CONFIG = {
  simulation: {
    fixedStepSeconds: 1 / 60,
    maxSubSteps: 3,
  },
  world: {
    blocksX: 10,
    blocksZ: 10,
    blockSize: 80,
    roadWidth: 40,
    sidewalkWidth: 2,
    boundaryPadding: 30,
    spatialCellSize: 64,
  },
  player: {
    length: 5.8,
    width: 3.1,
    acceleration: 13.2,
    highSpeedAcceleration: 4.1,
    accelerationFalloffPower: 1.45,
    reverseAcceleration: 7,
    braking: 18,
    rollingResistance: 0.75,
    aerodynamicDrag: 0.00022,
    maxForwardSpeed: 90,
    maxReverseSpeed: 18,
    lowSpeedYawRate: 1.45,
    highSpeedYawRate: 0.68,
    steeringResponse: 5.6,
    counterSteerResponseMultiplier: 1.7,
    minimumSteeringSpeed: 0.6,
    fullSteeringSpeed: 9,
    lateralGrip: 8.5,
    slidingGrip: 1.15,
    maxLateralAcceleration: 46,
    brakeGripLoss: 0.48,
    spinOutTorque: 2.1,
    brakeOversteer: 0.85,
    yawRecovery: 2.8,
    maxYawRate: 2.35,
    collisionSpeedLoss: 0.45,
    sidewalkHandlingMultiplier: 0.5,
    sidewalkGripMultiplier: 0.45,
    sidewalkExtraDrag: 18,
    radius: 2.15,
  },
  input: {
    steeringRiseRate: 4.2,
    steeringReturnRate: 6.5,
    pedalRiseRate: 5,
    pedalReturnRate: 8,
  },
  camera: {
    distance: 29,
    height: 17,
    lookAhead: 18,
    positionDamping: 7.5,
    targetDamping: 9,
    velocityInfluence: 0.16,
    minFov: 0.82,
    maxFov: 0.98,
  },
  traffic: {
    vehicleCount: 120,
    minSpeed: 10,
    maxSpeed: 17,
    radius: 1.9,
    lookAheadDistance: 9,
    spatialCellSize: 48,
    playerCollisionQueryRadius: 18,
    fullSimulationRadius: 280,
    reducedSimulationRadius: 600,
    reducedUpdateInterval: 0.2,
    recycleRadius: 720,
    respawnMinRadius: 380,
    respawnMaxRadius: 560,
    damageCooldownSeconds: 0.6,
  },
  fuel: {
    capacitySecondsAtCruise: 240,
    lowFuelThreshold: 0.2,
    refuelRadius: 16,
    refuelRatePerSecond: 0.2,
    fullTankCost: 50,
    refuelStopSpeedMph: 1,
    idleDrainMultiplier: 0.08,
    minMovingDrainMultiplier: 0.35,
    speedDrainMultiplier: 1.35,
    stationCount: 7,
  },
  repair: {
    shopCount: 3,
    repairRadius: 16,
    repairRatePerSecond: 0.2,
    fullRepairCost: 300,
    repairStopSpeedMph: 1,
    damageScaleSpeedMph: 130,
    maxCollisionDamage: 0.26,
  },
  map: {
    refreshSeconds: 0.5,
  },
  ride: {
    offerCount: 3,
    offerLifetimeSeconds: 60,
    offerDistanceRefreshSeconds: 1,
    maxPickupDistance: 300,
    minTripDistance: 190,
    tripTiers: {
      short: {
        minDistance: 180,
        maxDistance: 360,
      },
      medium: {
        minDistance: 420,
        maxDistance: 680,
      },
      long: {
        minDistance: 760,
        maxDistance: 1600,
      },
    },
    metersPerWorldUnit: 1,
    mphPerWorldUnitPerSecond: 1,
    pickupRadius: 7,
    destinationRadius: 7,
    rideResultSeconds: 2,
    fare: {
      baseFare: 3.75,
      ratePerMeter: 0.02,
      pickupDistanceWeight: 0.35,
      randomMultiplierMin: 0.7,
      randomMultiplierMax: 1.3,
      maxTipPercent: 0.5,
      tipDecayPercentPerSecond: 0.005,
    },
    passengerWeights: {
      normal: 0.65,
      scaredyCat: 0.25,
      speedDemon: 0.1,
    },
    satisfaction: {
      startingScore: 100,
      collisionCooldownSeconds: 5,
      collisionSpeedThresholdMph: 12,
      normal: {
        collisionPenalty: 40,
        maxSafeSpeedMph: 80,
        speedPenaltyPerSecond: 1,
      },
      scaredyCat: {
        collisionPenalty: 60,
        maxSafeSpeedMph: 50,
        speedPenaltyPerSecond: 1,
      },
      speedDemon: {
        collisionPenalty: 10,
        minRequiredSpeedMph: 25,
        speedPenaltyPerSecond: 1,
        gracePeriodSeconds: 5,
      },
    },
  },
} as const;
